DROP TABLE IF EXISTS page;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS file;
DROP TABLE IF EXISTS dictText;
DROP TABLE IF EXISTS dictWord;
DROP TABLE IF EXISTS offer;
DROP TABLE IF EXISTS dictIndex;
DROP TABLE IF EXISTS lang;