CREATE TABLE IF NOT EXISTS offer
(
	id INT AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	idImage INT,
	idTitle INT,
	idDescription INT,
	price DECIMAL(6, 2) NOT NULL,
	hours DECIMAL(5, 2) NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY(idImage) REFERENCES file(id) ON UPDATE CASCADE ON DELETE NULL,
	FOREIGN KEY(idTitle) REFERENCES dictIndex(id) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY(idDescription) REFERENCES dictIndex(id) ON UPDATE CASCADE ON DELETE SET NULL
) engine = InnoDB;