CREATE TABLE IF NOT EXISTS offer
(
	id INT AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	idImage INT,
	idTitle INT NOT NULL,
	idShortDescription INT NOT NULL,
	idDescription INT NOT NULL,
	map TEXT NOT NULL,
	idGallery INT,
	priceDC DECIMAL(6, 2),
	pricePC DECIMAL(6, 2),
	priceDV DECIMAL(6, 2),
	pricePV DECIMAL(6, 2),
	hours DECIMAL(5, 2) NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY(idTitle) REFERENCES dictIndex(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(idShortDescription) REFERENCES dictIndex(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(idDescription) REFERENCES dictIndex(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(idGallery) REFERENCES gallery(id) ON UPDATE CASCADE ON DELETE SET NULL
) engine = InnoDB;