CREATE TABLE IF NOT EXISTS page
(
	id INT AUTO_INCREMENT,
	file VARCHAR(255) NOT NULL,
	class VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(id),
	UNIQUE KEY(url)
) engine = InnoDB;
